package b2;

import b2.exception.CbException;
import b2.ui.Ui;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Test class for the Ui component of the B2 Super Battle Droid application.
 * Contains unit tests for validating user input and handling various commands such as adding tasks, listing tasks, marking tasks, deleting tasks, and finding tasks.
 * Ensures that the Ui component correctly processes user input and interacts with the TaskList and Storage components.
 * Test cases generated by GitHub Copilot Claude Sonnet 4.6
 */
public class B2SuperBattleDroidTest {

    private B2SuperBattleDroid b2;
    private Ui ui;

    @BeforeEach
    public void setUp() {
        File f = new File("data/test_tasks.txt");
        if (f.exists()) {
            f.delete();
        }
        b2 = new B2SuperBattleDroid("data/test_tasks.txt");
        ui = new Ui();
    }

    @AfterEach
    public void tearDown() {
        File f = new File("data/test_tasks.txt");
        if (f.exists()) {
            f.delete();
        }
    }

    // ==================== Ui.validate() tests ====================

    @Test
    public void validate_emptyInput_exceptionThrown() {
        String[] invalidInputs = {"", "   ", null};

        for (String invalidInput : invalidInputs) {
            try {
                ui.validate(invalidInput);
                fail("Expected CbException to be thrown for input: " + invalidInput);
            } catch (CbException e) {
                assertEquals("Error: Input cannot be empty!", e.getMessage());
            }
        }
    }

    // ==================== Todo tests ====================

    @Test
    public void getResponse_addTodoCommand_success() {
        String response = b2.getResponse("todo Read book");
        assertTrue(response.contains("Got it. I've added this task:"));
        assertTrue(response.contains("[T][ ] Read book"));
        assertTrue(response.contains("Now you have 1 tasks in the list."));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addTodoNoDescription_errorReturned() {
        String response = b2.getResponse("todo ");
        assertTrue(response.contains("Error: The description cannot be empty! Usage: todo <description>"));
        assertTrue(b2.getLastResponseWasError());
    }

    // ==================== Deadline tests ====================

    @Test
    public void getResponse_addDeadlineCommand_success() {
        String response = b2.getResponse("deadline Submit assignment /by 30/01/2026 2359");
        assertTrue(response.contains("Got it. I've added this task:"));
        assertTrue(response.contains("[D][ ] Submit assignment"));
        assertTrue(response.contains("Jan 30 2026"));
        assertTrue(response.contains("Now you have 1 tasks in the list."));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addDeadlineNoDescription_errorReturned() {
        String response = b2.getResponse("deadline ");
        assertTrue(response.contains("Error: The description cannot be empty! Usage: deadline <description> /by <deadline>"));
        assertTrue(b2.getLastResponseWasError());
    }


    @Test
    public void getResponse_addDeadlineNoDateTime_errorReturned() {
        String response = b2.getResponse("deadline Submit assignment");
        assertTrue(response.contains("Error: The deadline cannot be empty! Usage: deadline <description> /by <deadline>"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addDeadlineInvalidDateTime_errorReturned() {
        String response = b2.getResponse("deadline Submit assignment /by invaliddatetime");
        assertTrue(response.contains("Error: Invalid date/time format! Accepted formats are dd/MM/yyyy HHmm or dd-MM-yyyy HHmm"));
        assertTrue(b2.getLastResponseWasError());
    }

    // ==================== Event tests ====================

    @Test
    public void getResponse_addEventCommand_success() {
        String response = b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");
        assertTrue(response.contains("Got it. I've added this task:"));
        assertTrue(response.contains("[E][ ] Team meeting"));
        assertTrue(response.contains("Jan 31 2026"));
        assertTrue(response.contains("Now you have 1 tasks in the list."));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addEventNoDescription_errorReturned() {
        String response = b2.getResponse("event ");
        assertTrue(response.contains("Error: The description cannot be empty! Usage: event <description> /from <start time> /to <end time>"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addEventNoStartTime_errorReturned() {
        String response = b2.getResponse("event Team meeting");
        assertTrue(response.contains("Error: The start time cannot be empty! Usage: event <description> /from <start time> /to <end time>"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addEventNoEndTime_errorReturned() {
        String response = b2.getResponse("event Team meeting /from 31/01/2026 1400");
        assertTrue(response.contains("Error: The end time cannot be empty! Usage: event <description> /from <start time> /to <end time>"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addEventEndBeforeStart_errorReturned() {
        String response = b2.getResponse("event Team meeting /from 31/01/2026 1600 /to 31/01/2026 1400");
        assertTrue(response.contains("Error: End time cannot be earlier than start time!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_addEventInvalidStartDateTime_errorReturned() {
        String response = b2.getResponse("event Team meeting /from invaliddatetime /to 31/01/2026 1600");
        assertTrue(response.contains("Error: Invalid date/time format! Accepted formats are dd/MM/yyyy HHmm or dd-MM-yyyy HHmm"));
        assertTrue(b2.getLastResponseWasError());
    }

    // ==================== List tests ====================

    @Test
    public void getResponse_listCommand_success() {
        b2.getResponse("todo Read book");
        b2.getResponse("deadline Submit assignment /by 30/01/2026 2359");
        b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");

        String response = b2.getResponse("list");
        assertTrue(response.contains("Here are the tasks in your list:"));
        assertTrue(response.contains("[T][ ] Read book"));
        assertTrue(response.contains("[D][ ] Submit assignment"));
        assertTrue(response.contains("[E][ ] Team meeting"));
        assertFalse(b2.getLastResponseWasError());
    }

    // ==================== Mark/Unmark tests ====================

    @Test
    public void getResponse_markCommand_success() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("mark 1");
        assertTrue(response.contains("Nice! I've marked this task as done:"));
        assertTrue(response.contains("[T][X] Read book"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_markCommand_invalidIndex_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("mark 2");
        assertTrue(response.contains("Error: Invalid task index!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_unmarkCommand_success() {
        b2.getResponse("todo Read book");
        b2.getResponse("mark 1");
        String response = b2.getResponse("unmark 1");
        assertTrue(response.contains("OK, I've marked this task as not done yet:"));
        assertTrue(response.contains("[T][ ] Read book"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_unmarkCommand_invalidIndex_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("unmark 2");
        assertTrue(response.contains("Error: Invalid task index!"));
        assertTrue(b2.getLastResponseWasError());
    }

    // ==================== Delete tests ====================

    @Test
    public void getResponse_deleteCommand_success() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("delete 1");
        assertTrue(response.contains("Noted. I've removed this task:"));
        assertTrue(response.contains("[T][ ] Read book"));
        assertTrue(response.contains("Now you have 0 tasks in the list."));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_deleteCommand_invalidIndex_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("delete 2");
        assertTrue(response.contains("Error: Invalid task index!"));
        assertTrue(b2.getLastResponseWasError());
    }

    // ==================== Find tests ====================

    @Test
    public void getResponse_findCommand_success() {
        b2.getResponse("todo Read book");
        b2.getResponse("todo Buy groceries");
        String response = b2.getResponse("find book");
        assertTrue(response.contains("Here are the matching tasks in your list:"));
        assertTrue(response.contains("1. [T][ ] Read book"));
        assertFalse(response.contains("Buy groceries"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_findCommand_caseInsensitive() {
        b2.getResponse("todo READ BOOK");
        String response = b2.getResponse("find book");
        assertTrue(response.contains("Here are the matching tasks in your list:"));
        assertTrue(response.contains("1. [T][ ] READ BOOK"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_findCommand_noMatches() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("find groceries");
        assertTrue(response.contains("Here are the matching tasks in your list:"));
        assertTrue(response.contains("No matching tasks found!"));
        assertFalse(b2.getLastResponseWasError());
    }

    // ==================== Invalid command tests ====================

    @Test
    public void getResponse_invalidCommand_errorReturned() {
        String response = b2.getResponse("invalidcommand");
        assertEquals("Error: invalid command!", response);
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_emptyInput_errorReturned() {
        String response = b2.getResponse("");
        assertTrue(response.contains("Error: Input cannot be empty!"));
        assertTrue(b2.getLastResponseWasError());
    }

    // ==================== Edit tests ====================

    @Test
    public void getResponse_editTodoDescription_success() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 1 description Read magazine");
        assertTrue(response.contains("Noted. I've edited this task:"));
        assertTrue(response.contains("[T][ ] Read magazine"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editTodoDescription_emptyDescription_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 1 description ");
        assertTrue(response.contains("Error: Updated information cannot be empty! Usage: edit <task index> <field: description/by/from/to> <new value>"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editDeadlineDescription_success() {
        b2.getResponse("deadline Submit assignment /by 30/01/2026 2359");
        String response = b2.getResponse("edit 1 description Submit report");
        assertTrue(response.contains("Noted. I've edited this task:"));
        assertTrue(response.contains("[D][ ] Submit report (by: Jan 30 2026 2359)"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editDeadlineBy_success() {
        b2.getResponse("deadline Submit assignment /by 30/01/2026 2359");
        String response = b2.getResponse("edit 1 by 25-02-2026 2359");
        assertTrue(response.contains("Noted. I've edited this task:"));
        assertTrue(response.contains("[D][ ] Submit assignment (by: Feb 25 2026 2359)"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editDeadlineBy_invalidDateTime_errorReturned() {
        b2.getResponse("deadline Submit assignment /by 30/01/2026 2359");
        String response = b2.getResponse("edit 1 by invaliddatetime");
        assertTrue(response.contains("Error: Invalid date/time format! Accepted formats are dd/MM/yyyy HHmm or dd-MM-yyyy HHmm"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editDeadlineBy_onTodoTask_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 1 by 25-02-2026 2359");
        assertTrue(response.contains("Error: Only Deadline tasks have a deadline!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventDescription_success() {
        b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");
        String response = b2.getResponse("edit 1 description Board meeting");
        assertTrue(response.contains("Noted. I've edited this task:"));
        assertTrue(response.contains("[E][ ] Board meeting (from: Jan 31 2026 1400 to: Jan 31 2026 1600)"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventFrom_success() {
        b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");
        String response = b2.getResponse("edit 1 from 31/01/2026 1300");
        assertTrue(response.contains("Noted. I've edited this task:"));
        assertTrue(response.contains("[E][ ] Team meeting (from: Jan 31 2026 1300 to: Jan 31 2026 1600)"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventFrom_afterEndTime_errorReturned() {
        b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");
        String response = b2.getResponse("edit 1 from 31/01/2026 1700");
        assertTrue(response.contains("Error: Start time cannot be later than the existing end time (Jan 31 2026 1600)!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventFrom_onTodoTask_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 1 from 31/01/2026 1400");
        assertTrue(response.contains("Error: Only Event tasks have a start time!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventTo_success() {
        b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");
        String response = b2.getResponse("edit 1 to 31/01/2026 1700");
        assertTrue(response.contains("Noted. I've edited this task:"));
        assertTrue(response.contains("[E][ ] Team meeting (from: Jan 31 2026 1400 to: Jan 31 2026 1700)"));
        assertFalse(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventTo_beforeStartTime_errorReturned() {
        b2.getResponse("event Team meeting /from 31/01/2026 1400 /to 31/01/2026 1600");
        String response = b2.getResponse("edit 1 to 31/01/2026 1300");
        assertTrue(response.contains("Error: End time cannot be earlier than the existing start time (Jan 31 2026 1400)!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editEventTo_onTodoTask_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 1 to 31/01/2026 1600");
        assertTrue(response.contains("Error: Only Event tasks have an end time!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editCommand_invalidIndex_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 2 description New description");
        assertTrue(response.contains("Error: Invalid task index!"));
        assertTrue(b2.getLastResponseWasError());
    }

    @Test
    public void getResponse_editCommand_invalidField_errorReturned() {
        b2.getResponse("todo Read book");
        String response = b2.getResponse("edit 1 invalidfield New value");
        assertTrue(response.contains("Error: Invalid component to edit!"));
        assertTrue(b2.getLastResponseWasError());
    }
}
